# Generated by Django 4.2.3 on 2023-09-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_alter_vacancy_company_skill_phrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
