# Generated by Django 4.2.3 on 2023-09-04 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_remove_skill_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='keyword',
        ),
        migrations.AddField(
            model_name='graph',
            name='skill',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='scraping.skill'),
        ),
    ]
