# Generated by Django 4.0.5 on 2023-11-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0013_country_alter_state_abbreviation_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
