# Generated by Django 4.2.3 on 2023-11-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0015_city_female_population_city_male_population'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='population',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
