# Generated by Django 4.0.5 on 2023-11-27 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0017_country_gdp_usd_country_population'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='company',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='has_salary',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_max',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_min',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='yearly_salary',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='country',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='scraping.country'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='state',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='scraping.state'),
        ),
        migrations.DeleteModel(
            name='Vacancy_skill',
        ),
    ]
