# Generated by Django 4.0.5 on 2023-11-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0018_remove_vacancy_company_remove_vacancy_has_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='country',
            name='gdp_usd',
        ),
        migrations.RemoveField(
            model_name='country',
            name='population',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
