# Generated by Django 4.2.7 on 2023-12-01 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0024_availablevacancies_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='jobtitle',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='scraping.jobtitle'),
        ),
    ]
