# Generated by Django 4.2.7 on 2023-12-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0025_vacancy_jobtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='timestamp',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
