# Generated by Django 4.2.3 on 2023-09-03 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_skill_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='slug',
        ),
    ]
