# Generated by Django 4.2.3 on 2023-09-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0006_remove_graph_keyword_graph_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='city',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='country',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='job_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.BigIntegerField(blank=True),
        ),
    ]
