# Generated by Django 4.2.3 on 2023-09-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0007_alter_vacancy_city_alter_vacancy_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
