# Generated by Django 4.0.5 on 2023-11-14 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0011_company_alter_vacancy_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(blank=True, max_length=2)),
                ('name', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='city',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='country',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scraping.state'),
        ),
    ]
