# Generated by Django 4.0.5 on 2023-11-14 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0012_state_remove_vacancy_city_remove_vacancy_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(blank=True, max_length=5, unique=True)),
                ('name', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='state',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=2, unique=True),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, unique=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scraping.country')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scraping.state')),
            ],
        ),
    ]
