# Generated by Django 4.2.3 on 2023-11-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0014_alter_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='female_population',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='city',
            name='male_population',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
