# Generated by Django 4.0.5 on 2023-11-27 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0020_occuppationuri'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OccuppationUri',
            new_name='OccupationUri',
        ),
    ]
